=== m-nasiruddin/BengaliLexicalDisambiguationGoldStandard/GS_for_Bangla/SemEval/trial 2/data/multilingual-all-words.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!ELEMENT corpus (text+)>
<!ATTLIST corpus lang CDATA #REQUIRED>

<!ELEMENT text (sentence+)>
<!ATTLIST text id ID #REQUIRED>
<!ATTLIST text source CDATA #REQUIRED>

<!ELEMENT sentence (#PCDATA | instance | wf)*>
<!ATTLIST sentence id ID #REQUIRED>

<!ELEMENT wf (#PCDATA)>
<!ATTLIST wf lemma CDATA #REQUIRED>
<!ATTLIST wf pos CDATA #REQUIRED>

<!ELEMENT instance (#PCDATA)>
<!ATTLIST instance id ID #REQUIRED>
<!ATTLIST instance lemma CDATA #REQUIRED>
<!ATTLIST instance pos CDATA #REQUIRED>

=== m-nasiruddin/BengaliLexicalDisambiguationGoldStandard/GS_for_Bangla/SemEval/trial/data/multilingual-all-words.fr.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE corpus SYSTEM "multilingual-all-words.dtd">
<corpus lang="fr">
<text id="d001" source="wsj_2465">
  <sentence id="d001.s001">
    <wf lemma="nous" pos="PRO:PER">Nous</wf>
    <wf lemma="ne" pos="ADV">ne</wf>
    <wf lemma="savoir" pos="VER:pres">savons</wf>
    <wf lemma="pas" pos="ADV">pas</wf>
    <wf lemma="qui" pos="PRO:REL">qui</wf>
    <wf lemma="gagner" pos="VER:futu">gagnera</wf>
    <wf lemma="le" pos="DET:ART">la</wf>
    <instance id="d001.s001.t001" lemma="guerre_contre_la_drogue" pos="N">guerre_contre_la_drogue</instance>
    <wf lemma="en" pos="PRP">en</wf>
    <instance id="d001.s001.t002" lemma="Amérique_Latine" pos="N">Amérique_Latine</instance>
    <wf lemma="," pos="PUN">,</wf>
    <wf lemma="mais" pos="KON">mais</wf>
    <wf lemma="nous" pos="PRO:PER">nous</wf>
    <wf lemma="savoir" pos="VER:pres">savons</wf>
    <wf lemma="qui" pos="PRO:REL">qui</wf>
    <wf lemma="être" pos="VER:pres">est</wf>
    <wf lemma="en" pos="PRP">en</wf>
    <wf lemma="train" pos="NOM">train</wf>
    <wf lemma="de" pos="PRP">de</wf>
    <wf lemma="la" pos="PRO:PER">la</wf>
    <wf lemma="perdre" pos="VER:infi">perdre</wf>
    <wf lemma="-" pos="PUN">-</wf>
    <wf lemma="le" pos="DET:ART">la</wf>
    <instance id="d001.s001.t003" lemma="presse" pos="NOM">presse</instance>
    <wf lemma="." pos="SENT">.</wf>
  </sentence>
  <sentence id="d001.s002">
    <wf lemma="au" pos="PRP:det">Au</wf>
    <wf lemma="cour|cours" pos="NOM">cours</wf>
    <wf lemma="du" pos="PRP:det">des</wf>
    <wf lemma="six" pos="NUM">six</wf>
    <wf lemma="dernier" pos="ADJ">derniers</wf>
    <instance id="d001.s002.t001" lemma="mois" pos="NOM">mois</instance>
    <wf lemma="," pos="PUN">,</wf>
    <wf lemma="six" pos="NUM">six</wf>
    <instance id="d001.s002.t002" lemma="journaliste" pos="NOM">journalistes</instance>
    <wf lemma="avoir" pos="VER:pres">ont</wf>
    <wf lemma="être" pos="VER:pper">été</wf>
    <wf lemma="tuer" pos="VER:pper">tués</wf>
    <wf lemma="et" pos="KON">et</wf>
    <wf lemma="@card@" pos="NUM">10</wf>
    <wf lemma="avoir" pos="VER:pres">ont</wf>
    <wf lemma="être" pos="VER:pper">été</wf>
    <wf lemma="enlever" pos="VER:pper">enlevés</wf>
    <wf lemma="par" pos="PRP">par</wf>
    <wf lemma="du" pos="PRP:det">des</wf>
    <instance id="d001.s002.t003" lemma="trafiquant_de_drogue" pos="N">trafiquants_de_drogue</instance>
    <wf lemma="ou" pos="KON">ou</wf>
    <wf lemma="du" pos="PRP:det">des</wf>
    <instance id="d001.s002.t004" lemma="guérillero" pos="NOM">guérilleros</instance>
    <wf lemma="de" pos="PRP">de</wf>
    <instance id="d001.s002.t005" lemma="gauche" pos="NOM">gauche</instance>
    <wf lemma="-" pos="PUN">-</wf>
    <wf lemma="souvent" pos="ADV">souvent</wf>
    <wf lemma="il" pos="PRO:PER">il</wf>
    <wf lemma="s" pos="VER:futu">s</wf>
    <wf lemma="’" pos="PUN:cit">’</wf>
    <wf lemma="agir" pos="VER:pres">agit</wf>
    <wf lemma="du" pos="PRP:det">des</wf>
    <wf lemma="même" pos="ADJ">mêmes</wf>
    <instance id="d001.s002.t006" lemma="personne" pos="NOM">personnes</instance>
    <wf lemma="-" pos="PUN">-</wf>
    <wf lemma="en" pos="PRP">en</wf>
    <instance id="d001.s002.t007" lemma="Colombie" pos="NAM">Colombie</instance>
    <wf lemma="." pos="SENT">.</wf>
  </sentence>
  <sentence id="d001.s003">
    <wf lemma="au" pos="PRP:det">Au</wf>
    <wf lemma="cour|cours" pos="NOM">cours</wf>
    <wf lemma="du" pos="PRP:det">des</wf>
    <wf lemma="@card@" pos="NUM">12</wf>
    <wf lemma="dernier" pos="ADJ">dernières</wf>
    <instance id="d001.s003.t001" lemma="année" pos="NOM">années</instance>
    <wf lemma="," pos="PUN">,</wf>
    <wf lemma="au" pos="PRP:det">au</wf>
    <wf lemma="moins" pos="ADV">moins</wf>
    <wf lemma="@card@" pos="NUM">40</wf>
    <instance id="d001.s003.t002" lemma="journaliste" pos="NOM">journalistes</instance>
    <wf lemma="être" pos="VER:pres">sont</wf>
    <wf lemma="mourir" pos="VER:pper">morts</wf>
    <wf lemma="là-bas" pos="ADV">là-bas</wf>
    <wf lemma="." pos="SENT">.</wf>
  </sentence>
  <sentence id="d001.s004">
    <wf lemma="le" pos="DET:ART">Les</wf>
    <instance id="d001.s004.t001" lemma="attaque" pos="NOM">attaques</instance>
    <wf lemma="se" pos="PRO:PER">se</wf>
    <wf lemma="être" pos="VER:pres">sont</wf>
    <wf lemma="intensifier" pos="VER:pper">intensifiées</wf>
    <wf lemma="dès" pos="PRP">dès</wf>
    <wf lemma="que" pos="KON">que</wf>
    <wf lemma="le" pos="DET:ART">le</wf>
    <instance id="d001.s004.t002" lemma="gouvernement" pos="NOM">gouvernement</instance>
    <wf lemma="colombien" pos="ADJ">colombien</wf>
    <wf lemma="à" pos="PRP">à</wf>
    <wf lemma="commencer" pos="VER:pper">commencé</wf>
    <wf lemma="un" pos="DET:ART">une</wf>
    <instance id="d001.s004.t003" lemma="répression" pos="NOM">répression</instance>
    <wf lemma="muscler" pos="VER:pper">musclée</wf>
    <wf lemma="du" pos="PRP:det">des</wf>
    <instance id="d001.s004.t004" lemma="trafiquant" pos="NOM">trafiquants</instance>
    <wf lemma="en" pos="PRP">en</wf>
    <instance id="d001.s004.t005" lemma="août" pos="NOM">août</instance>
    <wf lemma="," pos="PUN">,</wf>
    <wf lemma="pour" pos="PRP">pour</wf>
    <wf lemma="tenter" pos="VER:infi">tenter</wf>
    <wf lemma="de" pos="PRP">d'</wf>
    <wf lemma="empêcher" pos="VER:infi">empêcher</wf>
    <wf lemma="qu" pos="VER:pper">qu</wf>
    <wf lemma="’" pos="PUN:cit">’</wf>
    <wf lemma="il" pos="PRO:PER">ils</wf>
    <wf lemma="prendre" pos="VER:pres">prennent</wf>
    <wf lemma="le" pos="DET:ART">le</wf>
    <instance id="d001.s004.t006" lemma="contrôle" pos="NOM">contrôle</instance>
    <wf lemma="du" pos="PRP:det">du</wf>
    <instance id="d001.s004.t007" lemma="pays" pos="NOM">pays</instance>
    <wf lemma="." pos="SENT">.</wf>
  </sentence>
  <sentence id="d001.s005">
    <wf lemma="le" pos="DET:ART">Le</wf>
    <instance id="d001.s005.t001" lemma="massacre" pos="NOM">massacre</instance>
    <wf lemma="en" pos="PRP">en</wf>
    <instance id="d001.s005.t002" lemma="Colombie" pos="NAM">Colombie</instance>
    <wf lemma="avoir" pos="VER:pres">a</wf>
    <wf lemma="être" pos="VER:pper">été</wf>
    <wf lemma="discuter" pos="VER:pper">discuté</wf>
    <wf lemma="par" pos="PRP">par</wf>
    <wf lemma="@card@" pos="NUM">450</wf>
    <instance id="d001.s005.t003" lemma="rédacteur" pos="NOM">rédacteurs</instance>
    <wf lemma="et" pos="KON">et</wf>
    <instance id="d001.s005.t004" lemma="éditeur" pos="NOM">éditeurs</instance>
    <wf lemma="de" pos="PRP">de</wf>
    <wf lemma="le" pos="DET:ART">l'</wf>
    <instance id="d001.s005.t005" lemma="Amérique_Latine" pos="NAM">Amérique_Latine</instance>
    <wf lemma="," pos="PUN">,</wf>
    <wf lemma="du" pos="PRP:det">des</wf>
    <instance id="d001.s005.t006" lemma="Etats-Unis" pos="NAM">Etats-Unis</instance>
    <wf lemma="," pos="PUN">,</wf>
    <wf lemma="du" pos="PRP:det">des</wf>
    <instance id="d001.s005.t007" lemma="Caraïbes" pos="NAM">Caraïbes</instance>
    <wf lemma="et" pos="KON">et</wf>
    <wf lemma="du" pos="PRP:det">du</wf>
    <instance id="d001.s005.t008" lemma="Canada" pos="NAM">Canada</instance>
    <wf lemma="qui" pos="PRO:REL">qui</wf>
    <wf lemma="avoir" pos="VER:pres">ont</wf>
    <wf lemma="participer" pos="VER:pper">participé</wf>
    <wf lemma="à" pos="PRP">à</wf>
    <wf lemma="le" pos="DET:ART">la</wf>
    <wf lemma="45ème" pos="ADJ">45ème</wf>
    <wf lemma="assemblée" pos="NOM">Assemblée</wf>
    <wf lemma="général" pos="ADJ">générale</wf>
    <wf lemma="de" pos="PRP">de</wf>
    <wf lemma="le" pos="DET:ART">l'</wf>
    <wf lemma="association" pos="NOM">Association</wf>
    <wf lemma="interaméricaine" pos="ADJ">interaméricaine</wf>
    <wf lemma="de" pos="PRP">de</wf>
    <wf lemma="le" pos="DET:ART">la</wf>
    <instance id="d001.s005.t009" lemma="presse" pos="NOM">presse</instance>
    <wf lemma="à" pos="PRP">à</wf>
    <instance id="d001.s005.t010" lemma="Monterrey" pos="NAM">Monterrey</instance>
    <wf lemma="," pos="PUN">,</wf>
    <wf lemma="au" pos="PRP:det">au</wf>
    <instance id="d001.s005.t011" lemma="Mexique" pos="NAM">Mexique</instance>
    <wf lemma="," pos="PUN">,</wf>
    <wf lemma="ce" pos="PRO:DEM">cette</wf>
    <wf lemma="semaine" pos="NOM">semaine</wf>
    <wf lemma="." pos="SENT">.</wf>
  </sentence>
  <sentence id="d001.s006">
    <wf lemma="le" pos="DET:ART">Le</wf>
    <instance id="d001.s006.t001" lemma="mardi" pos="NOM">mardi</instance>
    <wf lemma="," pos="PUN">,</wf>
    <wf lemma="le" pos="DET:ART">les</wf>
    <instance id="d001.s006.t002" lemma="participant" pos="NOM">participants</instance>
    <wf lemma="à" pos="PRP">à</wf>
    <wf lemma="le" pos="DET:ART">la</wf>
    <instance id="d001.s006.t003" lemma="conférence" pos="NOM">conférence</instance>
    <wf lemma="avoir" pos="VER:pres">ont</wf>
    <wf lemma="être" pos="VER:pper">été</wf>
    <wf lemma="informer" pos="VER:pper">informés</wf>
    <wf lemma="de" pos="PRP">d'</wf>
    <wf lemma="un" pos="DET:ART">une</wf>
    <wf lemma="autre" pos="ADJ">autre</wf>
    <wf lemma="atrocité" pos="NOM">atrocité</wf>
    <wf lemma="," pos="PUN">,</wf>
    <wf lemma="le" pos="DET:ART">l'</wf>
    <instance id="d001.s006.t004" lemma="assassinat" pos="NOM">assassinat</instance>
    <wf lemma="à" pos="PRP">à</wf>
    <instance id="d001.s006.t005" lemma="Medellin" pos="NAM">Medellin</instance>
    <wf lemma="de" pos="PRP">de</wf>
    <wf lemma="deux" pos="NUM">deux</wf>
    <instance id="d001.s006.t006" lemma="employé" pos="NOM">employés</instance>
    <wf lemma="de" pos="PRP">d'</wf>
    <instance id="d001.s006.t007" lemma="El_Espectador" pos="NAM">El_Espectador</instance>
    <wf lemma="," pos="PUN">,</wf>
    <wf lemma="le" pos="DET:ART">le</wf>
    <wf lemma="deuxième" pos="NUM">deuxième</wf>
    <wf lemma="plus" pos="ADV">plus</wf>
    <wf lemma="grand" pos="ADJ">grand</wf>
    <instance id="d001.s006.t008" lemma="journal" pos="NOM">journal</instance>
    <wf lemma="de" pos="PRP">de</wf>
